name: Latest Commits
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
workflow_dispatch:

jobs:
  update-readme-with-last-commit:
    name: Update this repo's README with latest commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: estarossa0/readme-last-commit@master